

#####################################################################################
# Find Helpers
#
unset( HELPERS_FOUND CACHE)

message( STATUS "HELPERS:") 
message( STATUS "  --> Looking for helpers here: HELPERS_DIR = ${HELPERS_DIR}") 	

set ( OK_HELP "0" )
_FIND_FILE ( HELPER_FILES HELPERS_DIR "nv_gui.h" "nv_gui.h" OK_HELP )

if ( OK_HELP EQUAL 1 )
    set ( HELPERS_FOUND "YES" )    
	include_directories( ${HELPERS_DIR} )	

	
	# OpenGL always required
	if ( REQUIRE_OPENGL )
		find_package(OpenGL)		
		message ( STATUS "  Using OpenGL")	
		message ( STATUS "    OPENGL from: ${OPENGL_LIBRARY}")
		add_definitions(-DUSE_OPENGL)
		LIST (APPEND PLATFORM_LIBRARIES ${OPENGL_LIBRARY} )
		# IF(WIN32)
		#   LIST(APPEND LIBRARIES_OPTIMIZED "opengl32.lib" )
		#   LIST(APPEND LIBRARIES_DEBUG "opengl32.lib" )
		# ENDIF()
	endif()

		#-------------------------------- Common Defs
	if ( REQUIRE_COMMON )
		message ( STATUS "  Using common_defs")
		add_definitions(-DUSE_COMMON)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/common_defs.cpp" )
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/common_defs.h" )	
	endif()

	#-------------------------------- Image formats
	if ( REQUIRE_PNG )				
	    # Add PNG to build
		message ( STATUS "  Using PNG")
		add_definitions(-DBUILD_PNG)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/file_png.cpp" )
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/file_png.h" )
	endif()
	if ( REQUIRE_TGA )
		# Add TGA to build
		message ( STATUS "  Using TGA")
		add_definitions(-DBUILD_TGA)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/file_tga.cpp" )	
	endif()
	if ( REQUIRE_JPG )
		message( STATUS "  Using JPG") 
		add_definitions(-DBUILD_JPG)
		message ( STATUS "    JPG from: ${COMBINED_INCLUDE_PATH}/libjpg")
		include_directories( "${COMBINED_INCLUDE_PATH}/libjpg" )	
		LIST(APPEND LIBRARIES_OPTIMIZED "${COMBINED_LIB_PATH}/libjpg_2019x64.lib" )
		LIST(APPEND LIBRARIES_DEBUG "${COMBINED_LIB_PATH}/libjpg_2019x64d.lib"  )	
	endif()
	if ( REQUIRE_TIF )
		message( STATUS "  Using TIF") 
		add_definitions(-DBUILD_TIF)		
	endif()
	#---------------------------------------- Graphics Libs	
	if ( REQUIRE_OPTIX )		
		message ( STATUS "  Using OPTIX_UTILS")		
		add_definitions(-DUSE_OPTIX_UTILS)		
		include_directories( "${HELPERS_DIR}/optix" )
		_FIND_MULTIPLE ( UTIL_OPTIX_FILES "${HELPERS_DIR}/optix" "cpp" "cpp" )
		_FIND_MULTIPLE ( UTIL_OPTIX_FILES "${HELPERS_DIR}/optix" "h" "h" )
		_FIND_MULTIPLE ( UTIL_OPTIX_KERNELS "${HELPERS_DIR}/optix" "cu" "cu" )
		_FIND_MULTIPLE ( UTIL_OPTIX_KERNELS "${HELPERS_DIR}/optix" "cuh" "cuh" )
		message ( STATUS "    OPTIX Helpers: ${UTIL_OPTIX_FILES};${UTIL_OPTIX_KERNELS}")
	endif()
	if ( REQUIRE_OPTIX7 )		
		message ( STATUS "  Using OPTIX7_UTILS")		
		add_definitions(-DUSE_OPTIX7_UTILS)
		include_directories( "${HELPERS_DIR}/optix7" )			
		_FIND_MULTIPLE ( UTIL_OPTIX7_FILES "${HELPERS_DIR}/optix7" "cpp" "cpp")
		_FIND_MULTIPLE ( UTIL_OPTIX7_FILES "${HELPERS_DIR}/optix7" "h" "h" )
		_FIND_MULTIPLE ( UTIL_OPTIX7_KERNELS "${HELPERS_DIR}/optix7" "cu" "cu" )
		_FIND_MULTIPLE ( UTIL_OPTIX7_KERNELS "${HELPERS_DIR}/optix7" "cuh" "cuh" )		
		message ( STATUS "    OPTIX Helpers: ${UTIL_OPTIX7_FILES};${UTIL_OPTIX7_KERNELS}")
	endif()
	if ( REQUIRE_GLEW )
		# Add GLEW to build
		message ( STATUS "  Using GLEW")
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/glew.c" )	
	endif()
	if ( REQUIRE_NVGUI )
		# Add NVGUI to build
		message ( STATUS "  Using NVGUI")
		add_definitions(-DUSE_NVGUI)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/nv_gui.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/nv_gui.h" )				
	endif()
	if ( REQUIRE_WIDGETS )
		# Add Widgets to build
		message ( STATUS "  Using Widget")
		add_definitions(-DUSE_WIDGETS)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/widget.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/widget.h" )				
	endif()
	if ( REQUIRE_CAM )
		# Add Camera to build
		message ( STATUS "  Using CAM")
		add_definitions(-DUSE_CAMERA)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/camera.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/camera.h" )				
	endif()
	if ( REQUIRE_VEC )
		# Add Vec to build
		message ( STATUS "  Using VEC")
		add_definitions(-DUSE_VEC_HELPER)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/vec.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/vec.h" )				
	endif()
	if ( REQUIRE_TIMEX )
		# Add Vec to build
		message ( STATUS "  Using TimeX")
		add_definitions(-DUSE_TIMEX)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/timex.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/timex.h" )				
	endif()
	#---------------------------------------- Strings & Dirs
	if ( REQUIRE_STRHELPER )
		message ( STATUS "  Using STR_HELPER")
		add_definitions(-DUSE_STR_HELPER)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/string_helper.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/string_helper.h" )		
	endif()
	if ( REQUIRE_DIRECTORY )
		message ( STATUS "  Using DIRECTORY")
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/directory.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/directory.h" )		
	endif()
	#---------------------------------------- Events & Network
	if ( REQUIRE_EVENTS )
		message ( STATUS "  Using Events")
		add_definitions(-DUSE_EVENTS)
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/event.cpp" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/event.h" )		
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/event_system.cpp" )
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/event_system.h" )	
	endif()
	if ( REQUIRE_NETWORK )
		message ( STATUS "  Using Network")
		add_definitions(-DUSE_NETWORK)		
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/network_socket.cpp" )
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/network_socket.h" )	
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/network_system.cpp" )
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/network_system.h" )	
	endif()
	#---------------------------------------- Main
	if ( REQUIRE_MAIN )
		# Add Main to build
		add_definitions(-DUSE_MAIN)
		IF(WIN32)
  			LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/main_win.cpp" )
	    ELSEIF(ANDROID)
			LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/main_android.cpp" )
		ELSE()
	  		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/main_x11.cpp" )
		ENDIF()
		LIST( APPEND UTIL_SOURCE_FILES "${HELPERS_DIR}/main.h" )
	endif()
	if ( REQUIRE_DPI_AWARE )
		add_definitions ( -DUSE_DPI_AWARE )
		LIST( APPEND PLATFORM_LIBRARIES "Shcore.lib" )
	endif()
else()
    set ( HELPERS_FOUND "NO" )	
	message ( FATAL_ERROR "
Helpers not found. Please set the CMAKE_MODULE_PATH to libraries/cmake \
and set HELPERS_DIR to libraries/helpers. \n
     ") 
endif()

message ( STATUS "  --> Using Helpers") 	

mark_as_advanced( HELPERS_FOUND )
